name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependeces
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
          sudo apt-get install git build-essential cmake automake libtool autoconf
          cd ..
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/scripts
          ./Configure linux-x86_64 no-shared
          ./build_deps.sh && cd ../build
          cmake .. -DXMRIG_DEPS=scripts/deps
          make -j$(nproc)
          
